server:
  port: 8081

spring:
  jpa:
    generate-ddl: true    # 项目启动时如果不存在表则新建表
    show-sql: true
    hibernate:
      ddl-auto: none    # 项目重启时不自动新建表

  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.46.59.190:5208/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: cris
    password: 970504

  # 微服务名称
  application:
    name: depart-provider

  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos注册中心地址
        username: nacos
        password: nacos
        ephemeral: false    # 默认是true表示临时实例，false为永久(只有在未注册的情况下才有作用)
#        enabled: false    # 不注册进入

# 日志
logging:
  pattern:    # 日志输出的格式
    console: level-%level %msg%n
  level:
    root: info    # 日志登记
    org.hibernate: info   # jpa底层是hibernate，所以输出设置为info
    top.cris15: debug   # 自己的代码日志设置为debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace    # show-sql=true时显示查询的sql语句
    org.hibernate.type.descriptor.sql.BasicExtractor: trace   # show-sql=true时显示查询参数